#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]

pub enum Opcode {
    Constant,
    Pop,
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    True,
    False,
    Equal,
    NotEqual,
    Greater,
    GreaterEq,
    Minus,
    Bang,
    Jump,
    JumpIfFalse,
    Null,
    DefineGlobal,
    GetGlobal,
    SetGlobal,
    Array,
    Map,
    GetIndex,
    SetIndex,
    Call,
    ReturnValue,
    Return,
    DefineLocal,
    GetLocal,
    SetLocal,
    GetBuiltinFn,
    GetBuiltinVar,
    Closure,
    GetFree,
    SetFree,
    CurrClosure,
    Not,
    And,
    Or,
    Xor,
    ShiftLeft,
    ShiftRight,
    #[default]
    Invalid,
}

impl From<u8> for Opcode {
    fn from(code: u8) -> Self {
        match code {
            0 => Opcode::Constant,
            1 => Opcode::Pop,
            2 => Opcode::Add,
            3 => Opcode::Sub,
            4 => Opcode::Mul,
            5 => Opcode::Div,
            6 => Opcode::Mod,
            7 => Opcode::True,
            8 => Opcode::False,
            9 => Opcode::Equal,
            10 => Opcode::NotEqual,
            11 => Opcode::Greater,
            12 => Opcode::GreaterEq,
            13 => Opcode::Minus,
            14 => Opcode::Bang,
            15 => Opcode::Jump,
            16 => Opcode::JumpIfFalse,
            17 => Opcode::Null,
            18 => Opcode::DefineGlobal,
            19 => Opcode::GetGlobal,
            20 => Opcode::SetGlobal,
            21 => Opcode::Array,
            22 => Opcode::Map,
            23 => Opcode::GetIndex,
            24 => Opcode::SetIndex,
            25 => Opcode::Call,
            26 => Opcode::ReturnValue,
            27 => Opcode::Return,
            28 => Opcode::DefineLocal,
            29 => Opcode::GetLocal,
            30 => Opcode::SetLocal,
            31 => Opcode::GetBuiltinFn,
            32 => Opcode::GetBuiltinVar,
            33 => Opcode::Closure,
            34 => Opcode::GetFree,
            35 => Opcode::SetFree,
            36 => Opcode::CurrClosure,
            37 => Opcode::Not,
            38 => Opcode::And,
            39 => Opcode::Or,
            40 => Opcode::Xor,
            41 => Opcode::ShiftLeft,
            42 => Opcode::ShiftRight,
            _ => Opcode::Invalid,
        }
    }
}

impl From<Opcode> for u8 {
    fn from(code: Opcode) -> Self {
        code as u8
    }
}
