name: Rust

on:
  push:
    branches: [ "main" ]
    # Rebuild On changes in 'src' or '.github' directory.
    paths:
      - 'src/**'
      - '.github/**'
  pull_request:
    branches: [ "main" ]
    # Rebuild On changes in 'src' or '.github' directory.
    paths:
      - 'src/**'
      - '.github/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
